version: '3'

services:
  pg-database:
    image: postgres:13
    environment:
      POSTGRES_USER: "root" 
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ny_taxi" 
    ports:
      - "5432:5432"
    volumes:
      - "${pwd}/data/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    # networks:
    #   - de-zoomcamp-postgres
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "8080:80"
    # networks:
    #   - de-zoomcamp-postgres

# networks: 
#   postgres-compose-network:
#     driver: bridge